import { IConfig, IProperty } from "./config.interface";
import moment from 'moment';
import uuid from 'uuid';
export const APP_NAME = "nestjs-starter";
const FILE_PROPERTY: IProperty = {
  name: "",
  type: "object",
  properties: [
    { name: "size", type: "number" },
    { name: "mimetype", type: "string" },
    { name: "path", type: "string" },
    { name: "fileName", type: "string" },
    { name: "bucket", type: "string" },
    { name: "etag", type: "string" },
    { name: "url", type: "string", required: true },
  ]
}

const configs: IConfig[] = [
  // {
  //   name: "conversation",
  //   output: "src/api/conversation/conversation",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "name", type: "string" },
  //     { name: "channel", type: "mongoId", ref: "Channel", required: true },
  //     { name: "user", type: "mongoId", ref: "User" },
  //     { name: "type", type: "string", enum: ['peer-to-peer', 'group', 'group-small'], default: 'peer-to-peer' },
  //     { name: "unread", type: "number", index: true },
  //     { name: "unreadMessage", type: "string", index: true },
  //     { name: "unreadFrom", type: "Date", index: true },
  //     { name: "users", type: "object", isArray: true, properties: [] },
  //   ],
  // },
  // {
  //   name: "conversation-user",
  //   output: "src/api/conversation/conversation-user",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "name", type: "string" },
  //     {
  //       ...FILE_PROPERTY,
  //       name: "avatar",
  //     },
  //     { name: "conversation", type: "mongoId", ref: "Conversation", required: true },
  //     { name: "user", type: "mongoId", ref: "User", required: true },
  //     { name: "role", type: "string", enum: ['owner', 'provider', 'user', 'patient', 'support', 'admin', 'guest'], default: 'guest', required: true },
  //     { name: "chatPolicy", type: "string", enum: ['allowed', 'readonly', 'restricted'], default: 'allowed' },
  //     { name: "state", type: "string", enum: ['active', 'inactive'], default: 'active' },
  //     { name: "search", type: "string" },
  //     { name: "otherUsers", type: "object", isArray: true, properties: [] },
  //   ],
  // },
  // {
  //   name: "diagnosis",
  //   output: "src/api/diagnosis/diagnosis",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "name", type: "string", required: true, unique: true, index: true },
  //     {
  //       name: "code",
  //       type: "object",
  //       properties: [
  //         { name: "icd10", type: "string" },
  //       ]
  //     },
  //     { name: "locale", type: "string", enum: ['vi', 'en'], default: 'vi' },
  //   ],
  // },
  // {
  //   name: "drug",
  //   output: "src/api/prescription/drug",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "name", type: "string", index: true, unique: true },
  //     { name: "state", type: "string", enum: ['draft', 'published'] },
  //     { name: "route", type: "string" },
  //     { name: "strength", type: "string" },
  //   ],
  // },
  // {
  //   name: "test",
  //   output: "src/api/test/test",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "name", type: "string", required: true },
  //     { name: "type", type: "string", required: true, enum: ["lab", "imaging"] },
  //     { name: "specimen", type: "string", enum: ["EDTA", "CIT", "S", "F", "P", "Đ", "D", "NT", "ESR tube", "ST/ SPECIFIC TUBE"] },
  //     { name: "tags", type: "string", isArray: true },
  //     {
  //       name: "code",
  //       type: "object",
  //       properties: [
  //         { name: "loinc", type: "string" },
  //       ]
  //     },
  //     { name: "abbreviation", type: "string" },
  //     { name: "locale", type: "string", enum: ['vi', 'en'], default: 'vi' },
  //   ],
  // },
  // {
  //   name: "test-request",
  //   output: "src/api/test/test-request",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "provider", type: "mongoId", ref: "Provider" },
  //     { name: "consultation", type: "mongoId", ref: "Consultation" },
  //     { name: "tests", type: "mongoId", ref: "Test", isArray: true },
  //     { name: "patient", type: "mongoId", ref: 'User' },
  //     // Research more
  //     { name: "state", type: "string", enum: ["new", "ordered", "result-ready"] },
  //     { name: "urgency", type: "string", enum: ["normal", "urgent"] },
  //     { name: "instructions", type: "string" },
  //   ],
  // },
  // {
  //   name: "test-result",
  //   output: "src/api/test/test-result",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "testRequest", type: "mongoId", ref: "TestRequest" },
  //     { name: "reportedAt", type: "Date" },
  //     { name: "patient", type: "mongoId", ref: 'User' },
  //     // Research more
  //     // Observation
  //     { name: "interpretation", type: "string" },
  //     { name: "instructions", type: "string" },
  //   ],
  // },
  // {
  //   name: "observation",
  //   output: "src/api/observation",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "type", type: "string", enum: ["test", "home-monitoring"] },
  //     { name: "user", type: "mongoId", ref: "User", required: true },
  //     { name: "test", type: "mongoId", ref: "Test" },
  //     { name: "testResult", type: "mongoId", ref: "TestResult" },
  //     { name: "key", type: "string" },
  //     { name: "value", type: "string", required: true },
  //     { name: "unit", type: "string" },
  //     { name: "status", type: "string", enum: ["draft", "published", "archived"] },
  //     { name: "isCalculated", type: "boolean", default: false },
  //     { name: "name", type: "string" },
  //     { name: "observedAt", type: "Date", required: true },
  //   ],
  // },
  // {
  //   name: "medical-reference",
  //   output: "src/api/prescription/medical-reference",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     {
  //       name: "name",
  //       type: "object",
  //       properties: [
  //         { name: "en", type: "string" },
  //         { name: "vi", type: "string" },
  //       ]
  //     },
  //     { name: "type", type: "string", enum: ['rxFrequency', 'routeOfAdministration', 'observation', 'other'] },
  //     { name: "value", type: "number" },
  //     { name: "order", type: "number" },
  //   ],
  // },
  // {
  //   name: "prescription",
  //   output: "src/api/prescription/prescription",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "user", type: "mongoId", ref: "User" },
  //     { name: "consultation", type: "mongoId", ref: "Consultation" },
  //     { name: "drug", type: "mongoId", ref: "Drug", required: true },
  //     { name: "route", type: "mongoId", ref: "MedicalReference" },
  //     { name: "take", type: "number" },
  //     { name: "unit", type: "string" },
  //     { name: "total", type: "number" },
  //     { name: "duration", type: "number" },
  //     { name: "frequency", type: "mongoId", ref: "MedicalReference" },
  //     { name: "note", type: "string" },
  //     { name: "followDirection", type: "boolean", default: false },
  //   ],
  // },
  // {
  //   name: "prescription-auto-fill",
  //   output: "src/api/prescription/prescription-auto-fill",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "provider", type: "mongoId", required: true, ref: "Provider" },
  //     { name: "drug", type: "mongoId", required: true, ref: "Drug" },
  //     { name: "prescription", type: "mongoId", required: true, ref: "Prescription" },
  //     { name: "route", type: "mongoId", ref: "MedicalReference" },
  //     { name: "take", type: "number" },
  //     { name: "unit", type: "string" },
  //     { name: "total", type: "number" },
  //     { name: "duration", type: "number" },
  //     { name: "frequency", type: "mongoId", ref: "MedicalReference" },
  //     { name: "note", type: "string" },
  //   ],
  // },
  // {
  //   name: "provider",
  //   output: "src/api/provider",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "name", type: "string", required: true },
  //     { name: "title", type: "string", enum: ['Bs', 'Bs.CK1', 'Bs.CK2', 'ThS.Bs', 'TS.Bs', 'PGS.Bs', 'GS.Bs', 'Ch.G.TL', 'ThS.TL', 'TLG'], default: 'Bs' },
  //     { name: "slug", type: "string", unique: true },
  //     { name: "active", type: "boolean", default: false },
  //     { name: "contract", type: "string", enum: ['waitingContract', 'sendContract', 'receivedContract'] },
  //     { name: "published", type: "boolean", default: false, index: true },
  //     { name: "spoken", type: "string", isArray: true },
  //     { name: "consultTime", type: "number", enum: [0, 10, 15, 20, 25, 30, 45, 60], default: 15 },
  //     { name: "bookingDelay", type: "number", default: 30 },
  //     { name: "adminOrder", type: "number", default: 0 },
  //     { name: "order", type: "number", min: 0, default: 0 },
  //     { name: "specialty", type: "mongoId", isArray: true, ref: "Specialty" },
  //     {
  //       ...FILE_PROPERTY,
  //       name: "avatar",
  //     },
  //     { name: "joinDate", type: "Date", index: true, default: () => moment() },
  //     {
  //       name: "profile",
  //       type: "object",
  //       properties: [
  //         { name: "education", type: "string" },
  //         { name: "experience", type: "string" },
  //         { name: "portrait", type: "string" },
  //         { name: "tagLine", type: "string" },
  //         { name: "diagnosis", type: "mongoId", ref: "Diagnosis", isArray: true },
  //         { name: "experiencesDescription", type: "string" },
  //         { name: "startWork", type: "Date", default: () => moment().subtract(5, "y") },
  //       ]
  //     },
  //     { name: "highlight", type: "string" },
  //     { name: "user", type: "mongoId", ref: "User", required: true },
  //     {
  //       name: "document",
  //       type: "object",
  //       properties: [
  //         { ...FILE_PROPERTY, name: "identity1" },
  //         { ...FILE_PROPERTY, name: "identity2" },
  //         { ...FILE_PROPERTY, name: "license" },
  //       ]
  //     },
  //     { name: "licenceNumber", type: "string" },
  //     { name: "identityNumber", type: "string" },
  //     { name: "tax", type: "string" },
  //     { name: "location", type: "mongoId", ref: "Location", isArray: true },
  //   ],
  // },
  // {
  //   name: "rating",
  //   output: "src/api/rating",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: false,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "ratingBy", type: "mongoId", ref: "User" },
  //     { name: "rating", type: "number", enum: [1, 2, 3, 4, 5] },
  //     { name: "comment", type: "string" },
  //     { name: "state", type: "string", enum: ['draft', 'published'], default: 'published' },
  //     { name: "consultation", type: "mongoId", ref: "Consultation" },
  //     { name: "provider", type: "mongoId", ref: "Provider" },
  //     { name: "sentiment", type: "string", enum: ['positive', 'negative', 'neutral'] },
  //     { name: "isFeature", type: "boolean", default: false },
  //     { name: "order", type: "number", default: 0 },
  //     { name: "showOnHomepage", type: "boolean", default: false },
  //   ],
  // },
  // {
  //   name: "user",
  //   output: "src/auth/user",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: false,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "name", type: "string", required: true, index: true },
  //     { name: "search", type: "string", default: 'User Information' },
  //     { name: "countryCode", type: "string", default: '84' },
  //     { name: "phone", type: "string" },
  //     { name: "gender", type: "string", enum: ['M', 'F', 'U', 'male', 'female'] },
  //     { name: "dob", type: "Date" },
  //     { name: "email", type: "string", index: true },
  //     {
  //       ...FILE_PROPERTY,
  //       name: "avatar",
  //     },
  //   ],
  // },
  // {
  //   name: "diagnosis-suggestion",
  //   output: "src/api/diagnosis/diagnosis-suggestion",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "user", type: "mongoId", ref: "User" },
  //     { name: "diagnosis", type: "mongoId", ref: "Diagnosis" },
  //     { name: "consultation", type: "mongoId", ref: "Consultation" },
  //   ],
  // },
  {
    name: "relationship",
    output: "src/api/user/relationship",
    controller: true,
    dto: true,
    schema: true,
    service: true,
    subscriber: false,
    "schema.publish-queue": true,
    "schema.publish-local": true,
    "schema.publish-socket": true,
    properties: [
      { name: "user", type: "mongoId", ref: "User", required: true },
      { name: "related", type: "mongoId", ref: "User", required: true },
      { name: "relationship", type: "string", enum: ['child', 'parent', 'sibling', 'spouse', 'doctor'], required: true },
    ],
  },
  // {
  //   name: "channel",
  //   output: "src/api/conversation/channel",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "name", type: "string" },
  //     { name: "platform", type: "string", enum: ['facebook', 'onemr', 'zalo'], default: 'facebook', required: true },
  //     { name: "provider", type: "mongoId", ref: "Provider" },
  //     { name: "unread", type: "number", default: 0 },
  //     { name: "picture", type: "string" },
  //     { name: "bot", type: "boolean", default: false },
  //     {
  //       name: "default",
  //       type: "object",
  //       properties: [
  //         { name: "corpus", type: "mongoId", ref: "Corpus" },
  //         { name: "waitToRespond", type: "number", min: 0, max: 60 * 60, default: 10 },
  //         { name: "chatSessionTimeout", type: "number", min: 0, max: (3 * 24 * 60), default: 120 },
  //       ]
  //     },
  //     {
  //       name: "facebook",
  //       type: "object",
  //       properties: [
  //         { name: "id", type: "string" },
  //         {
  //           name: "home_url",
  //           type: "object",
  //           properties: [
  //             { name: "url", type: "string", default: "https://fv.khamtuxa.vn" },
  //             { name: "webview_height_ratio", type: "string", enum: ["tall"], default: "tall" },
  //             { name: "webview_share_button", type: "string", enum: ["show", "hide"], default: "show" },
  //             { name: "in_test", type: "boolean", default: true },
  //           ]
  //         },
  //         { name: "access_token", type: "string" },
  //         { name: "persistent_menu", type: "string", default: "{}" },
  //         { name: "connectChannel", type: "boolean", default: false },
  //       ]
  //     },
  //   ],
  // },
  // {
  //   name: "favorite",
  //   output: "src/api/diagnosis/favorite",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": false,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": false,
  //   properties: [
  //     { name: "user", type: "mongoId", ref: "User", required: true },
  //     { name: "share", type: "boolean", default: false },
  //     { name: "type", type: "string", enum: ["variable", "user_filter", "conversation_search", "last_conversation", "diagnosis", "drug", "symptom", "ggsheet_report", "doctor_search"] },
  //     { name: "name", type: "string" },
  //     { name: "value", type: "string" },
  //     { name: "hit", type: "number" },
  //   ],
  // },
  // {
  //   name: "chart-template",
  //   output: "src/api/observation/chart-template",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "title", type: "string", required: true },
  //     { name: "slug", type: "string" },
  //     { name: "source", type: "string" },
  //     { name: "template", type: "string" },
  //   ],
  // },
  // {
  //   name: "patient-note",
  //   output: "src/api/observation/patient-note",
  //   controller: true,
  //   dto: true,
  //   schema: true,
  //   service: true,
  //   subscriber: true,
  //   "schema.publish-queue": true,
  //   "schema.publish-local": true,
  //   "schema.publish-socket": true,
  //   properties: [
  //     { name: "patient", type: "string", required: true },
  //     { name: "note", type: "string", required: true },      
  //     { name: "type", type: "string", enum : ['medical-history', 'allergies', 'current-medications'] }
  //   ],
  // },  
];

export default configs;
