export const Currencies = ["vnd", "usd"];
export const Locales = ["vi", "en"];
export const States = ["draft", "published", "archived"];
export const Roles = ["superadmin", "admin", "patient", "provider"];
export const MAIN_EXCHANGE = "ResourceEvent";
export const MAIN_ROLE = "master";
export const BASE_ROUTING_KEY = "consultation-server";
export const CITIES = [
  "An Giang",
  "Kon Tum",
  "Đắk Nông",
  "Sóc Trăng",
  "Bình Phước",
  "Hưng Yên",
  "Thanh Hóa",
  "Quảng Trị",
  "Tuyên Quang",
  "Quảng Ngãi",
  "Hà Nội",
  "Lào Cai",
  "Vĩnh Long",
  "Lâm Đồng",
  "Bình Định",
  "Nghệ An",
  "Kiên Giang",
  "Hà Giang",
  "Phú Yên",
  "Lạng Sơn",
  "Đà Nẵng",
  "Sơn La",
  "Tây Ninh",
  "Nam Định",
  "Lai Châu",
  "Bến Tre",
  "Khánh Hòa",
  "Bình Thuận",
  "Cao Bằng",
  "Hải Phòng",
  "Ninh Bình",
  "Yên Bái",
  "Gia Lai",
  "Hoà Bình",
  "Bà Rịa - Vũng Tàu",
  "Cà Mau",
  "Bình Dương",
  "Cần Thơ",
  "Thừa Thiên Huế",
  "Đồng Nai",
  "Tiền Giang",
  "Điện Biên",
  "Vĩnh Phúc",
  "Quảng Nam",
  "Đắk Lắk",
  "Thái Nguyên",
  "Hải Dương",
  "Bạc Liêu",
  "Trà Vinh",
  "Thái Bình",
  "Hà Tĩnh",
  "Ninh Thuận",
  "Đồng Tháp",
  "Long An",
  "Hậu Giang",
  "Quảng Ninh",
  "Phú Thọ",
  "Quảng Bình",
  "Hồ Chí Minh",
  "Hà Nam",
  "Bắc Ninh",
  "Bắc Giang",
  "Bắc Kạn",
];
